### ISSUE TITLE
How do you include pseudo selectors?

### ISSUE THREAD

**Issue by DTwigs** [zgabievi/bem#3] opened 2016-03-01 18:46 UTC
I'm having some trouble figuring out how to incorporate pseudo selectors and also how to share styles between multiple modifiers.

How do I write something like this with sass-bem?

```
.block {
  display: blockish;
}

.block:hover, .block--hover {
  display: hover-state;
}
```

**Comment by zgabievi** [comment] 2016-03-01 20:02
Hi @DTwigs, to do this your code should look like this:

``` scss
// .block
@include b(block) {
    display: blockish;

    // .block:hover
    @include hover {
        display: hover-state;
    }

    // .block--hover
    @include m(hover) {
        display: hover-state;
    }
}
```

There is no way to write this two selectors separated by comma yet, but I'm going to add this support.

**Comment by DTwigs** [comment] 2016-03-01 22:27
Thanks for the help!

**Comment by zgabievi** [comment] 2016-03-02 06:48
You are welcome!

**Comment by DTwigs** [comment] 2016-03-07 18:10
Hi @zgabievi, I'm on the cusp of deciding to migrate our whole site to sass-bem. I am curious if you have a time line as to when you could implement the multi selector mixins?

**Comment by zgabievi** [comment] 2016-03-09 08:52
Hi @DTwigs, I've created parse() mixin, which is in 61fc0dbec594a6912003bf3fcf0ef5bee7a86825. I'll write some documentation and than will be change version to 2.3.0

**Comment by DTwigs** [comment] 2016-03-09 18:38
Oh sweet, I'll check it out.  Thanks!

**Comment by DTwigs** [comment] 2016-03-09 19:17
This is looking pretty good but I think there is a bug.  The parse method is outputting the modifier classes without the base block class.  It is also adding the styles from the modifier to the block style.

```
@include b('button') {
  background-color: red;

  @include parse('m:hover', ':hover') {
    color: blue;
  }
}
```

outputs:

```
.button {
  background-color: red;
  color: blue;
}

--hover, .button:hover {
  color: blue;
}
```

So it looks like the `m:hover` isn't appending the block name.  Am I using this correctly?

**Comment by zgabievi** [comment] 2016-03-10 07:23
I've made some changes, but I couldn't reproduce your issue. Can you try this one more time with [2.3.1](https://github.com/zgabievi/sass-bem/releases/tag/2.3.1) release? Changes are in 9f0bc610a8f088a303207ea495095c1d5f70490d

**Comment by DTwigs** [comment] 2016-03-10 17:14
Looking good.  The most recent changes have fixed the issue that I was seeing.  I'm going to start working on translating our project over to sass-bem.  Thank you very much!

**Comment by DTwigs** [comment] 2016-03-10 18:30
As I'm going through I have a couple questions.

How can I write this in sass-bem?

```
.button {
  &,
  &--small {
    color: blue;
  }
}
```

Is there a way to write that without repeating `color: blue`?

One more scenario:

```
.button {
  &--disabled, &[disabled] {
    background-color: grey;
  }
}
```

Since `[disabled]` is an attribute selector and not a pseudo selector, is there a way to write that with sass-bem?

**Comment by zgabievi** [comment] 2016-03-10 20:05
First please update to [2.3.2](https://github.com/zgabievi/sass-bem/releases/tag/2.3.2), or follow this commit 73234b229054497067ab529b67f869437a44cc51;

For the first question, use:

``` sass
@include b('button') {
    @include parse('b:button', 'm:small') {
        color: blue;
    }
}
```

Outputs:

``` css
.button, .button--small {
    color: blue;
}
```

---

Second scenario:

``` sass
@include b('button') {
    @include parse('m:disabled', '[disabled]') {
        background-color: grey;
    }
}
```

Outputs:

``` css
.button--disabled, .button[disabled] {
    background-color: grey;
}
```

**Comment by DTwigs** [comment] 2016-03-10 21:18
Wow, you are on top of this.  Thanks!  This is great!

I am having trouble installing the 2.3.2 version.  Did you publish it to npm?

```
npm ERR! No compatible version found: sass-bem@^2.3.2
npm ERR! Valid install targets:
npm ERR! 2.3.1, 2.3.0, 2.2.1, 2.2.0, 2.1.1, 2.1.0, 1.0.0, 0.2.1, 0.2.0
```

**Comment by zgabievi** [comment] 2016-03-11 07:22
Sorry, I was pretty sure that I published it :D

**Comment by zgabievi** [comment] 2016-03-11 07:26
There you go [NPM](https://www.npmjs.com/package/sass-bem)

**Comment by DTwigs** [comment] 2016-03-11 18:12
Haha thanks!

I have another request, instead of using `@include parse('b:blockName')` to mimic the `& { }` can we use `@include parse('&')`?

This would make it so we can do this for blocks, elements, and modifiers.

Right now in the code there is a little shortcut where you can type `@include parse(' ')` and it has the same effect, but I'd prefer to not use an empty space and use an `&` so it's more explicit and familiar.  What do you think?

**Comment by zgabievi** [comment] 2016-03-11 20:08
Great idea. I'll do that ;)

**Comment by zgabievi** [comment] 2016-03-11 21:05
Now you can upgrade to `2.3.3` and use `&` symbol in parse mixin. I'll close this issue for now ;)

**Closed as completed by zgabievi** 2016-03-11 21:05 UTC
Labels: enhancement
